### ISSUE TITLE
Window shuts down after setting time between clicks

### ISSUE THREAD

**Issue by martas4444** [InfamyStudio/lostArkAntiAFKBot#2]
Hi,

First of all, thank you very much for this contribution and effort.

I have run into some issue when trying get this to work.
I have managed to install python/pip and autogui.
When I open Obfuscated.py it shows the CMD, detects my resolution and let me choose keys + time between clicks.

But when switching back to game and waiting for some time, the windows just shut down and nothing happens. Can you please help ? 

Thank you very much

**Comment by InfamyStudio** [comment]
Hi,

Thank you for your response!

Would you be able to record the issue for me, as of right now the program is working as intended for me across all versions (V1.0,V1.1,V1.2)

Important to note that wherever the mouse cursor is the program executes within. It also only works on display 1 as if you have dual screens for example the play area would be in the minus res so -1920

**Comment by InfamyStudio** [comment]
If it is a time between clicks issue, the latest version should have patched all of the bugs with user input. The input is in seconds and to test this you could do lowest time as 1 second and highest time as 10 to see if the program executes for you correctly!

**Comment by martas4444** [comment]
Wow, thanks for that fast response!

I am using 3 monitors. Lost ark is running on middle monitor which is labeled as "2" when going to settings > rearrange your displays.
So, that might cause the issue?
Should I try to change this to display 1 or only solution is to disconnect the rest of 2 monitors?

**Comment by InfamyStudio** [comment]
I think you would definitely need that to be identified as display 1, as otherwise with 3 at 1920 it would run like left to right. So first monitor would be -1920x-1080, second 1920x1080, third 3840x2160

I will look into creating a patch as well for multiple display users but I am also going under the assumption that usually display 1 is your main gaming monitor!

**Comment by InfamyStudio** [comment]
Let me know how it goes please!

**Comment by InfamyStudio** [comment]
Could you record a video of the what is happening with it please, or screenshot of what is displayed on the program. Or please open the program with python idle. So right click on the program and click edit with idle. Then click F5 for me when in idle, click through the options and when it crashes it will show the debug output or error!

**Comment by martas4444** [comment]
Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

=============== RESTART: C:\Program Files (x86)\AMD\Obfuscated.py ==============
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Using 2560x1440, Changing Randomx and Randomy
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The Default Button Click List Is:
['q', 'w', 'e', 'r', 'a', 's', 'd', 'f']
Would You Like To Add More Keys To The ButtonClickList? Enter (Y) or (N): n
The Button Click List Is: 
['q', 'w', 'e', 'r', 'a', 's', 'd', 'f']
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Usage Just Type an Integer e.g. 30
Please Enter The Shortest Amount of Seconds To Wait Before Input - Recommended (30 seconds): 30
Please Enter The Longest Amount of Seconds To Wait Before Input - Recommended (1200 seconds): 120
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Time Waiting Before Next Interaction: 98 second(s) or 1.6333333333333333 minute(s)!
Traceback (most recent call last):
  File "C:\Users\Marťas\AppData\Local\Programs\Python\Python310\lib\random.py", line 303, in randrange
    istart = _index(start)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\AMD\Obfuscated.py", line 60, in <module>
    while F :I (K );R (U );I (K );T (J )
  File "C:\Program Files (x86)\AMD\Obfuscated.py", line 39, in R
    def R (OOOO0OO00O00OO0O0 ):O00OOOO00O000OOO0 =OOOO0OO00O00OO0O0 ;O0OO0O00O000000OO =Q (O00OOOO00O000OOO0 );O0000O00OOO000OO0 =O0OO0O00O000000OO [0 ];OO000O0OO0OOO000O =O0OO0O00O000000OO [1 ];H .moveTo (O0000O00OOO000OO0 ,OO000O0OO0OOO000O );H .click ();A ('Mouse Clicked At: ('+B (O0000O00OOO000OO0 )+','+B (OO000O0OO0OOO000O )+')')#line:39
  File "C:\Program Files (x86)\AMD\Obfuscated.py", line 38, in Q
    def Q (O0OO00OO00O000OO0 ):O00O00O000OO0000O =O0OO00OO00O000OO0 ;O0OO0OO0OO0O0OO0O =C (O00O00O000OO0000O [0 ],O00O00O000OO0000O [1 ]);O0OOO0O00O0000O0O =C (O00O00O000OO0000O [2 ],O00O00O000OO0000O [3 ]);return O0OO0OO0OO0O0OO0O ,O0OOO0O00O0000O0O #line:38
  File "C:\Users\Marťas\AppData\Local\Programs\Python\Python310\lib\random.py", line 370, in randint
    return self.randrange(a, b+1)
  File "C:\Users\Marťas\AppData\Local\Programs\Python\Python310\lib\random.py", line 309, in randrange
    raise ValueError("non-integer arg 1 for randrange()")
ValueError: non-integer arg 1 for randrange()

**Comment by Racle** [comment]
> I will look into creating a patch as well for multiple display users but I am also going under the assumption that usually display 1 is your main gaming monitor!

Seems to be related to which port you have your monitor connected. 
Got 3 screens also and my main monitor is identified as 2, but is configured to be main display.

Script still seems to be using my main monitor as it complains for non-supported res (and manually printing out shows `Size(width=5120, height=1440)`). I'm using Windows 11

And it seems that you're missing (super)ultra wide resolutions (5120x1440 and 3440x1440).

Game is still running middle of my screen with black bars on the side, so I believe that with my 5120x1440 resolution game display area is only 3440x1440.

**Comment by martas4444** [comment]
I am on Windows 10
monitor that is lost ark running on is also set as my main monitor

**Comment by martas4444** [comment]
I have tried to run "minified" version. Will post results down below.
Is it possible that it can be also caused by that Lost ark is running in Borderless mode?
When I set game for full screen it completely breaks and shows just strip of the game.
----
Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

================ RESTART: C:\Program Files (x86)\AMD\Minified.py ===============
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Using 2560x1440, Changing Randomx and Randomy
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The Default Button Click List Is:
['q', 'w', 'e', 'r', 'a', 's', 'd', 'f']
Would You Like To Add More Keys To The ButtonClickList? Enter (Y) or (N): n
The Button Click List Is: 
['q', 'w', 'e', 'r', 'a', 's', 'd', 'f']
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Usage Just Type an Integer e.g. 30
Please Enter The Shortest Amount of Seconds To Wait Before Input - Recommended (30 seconds): 30
Please Enter The Longest Amount of Seconds To Wait Before Input - Recommended (1200 seconds): 120
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Time Waiting Before Next Interaction: 50 second(s) or 0.8333333333333334 minute(s)!
Traceback (most recent call last):
  File "C:\Users\Marťas\AppData\Local\Programs\Python\Python310\lib\random.py", line 303, in randrange
    istart = _index(start)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\AMD\Minified.py", line 60, in <module>
    while F:I(K);R(U);I(K);T(J)
  File "C:\Program Files (x86)\AMD\Minified.py", line 39, in R
    def R(retScreenSize):F=retScreenSize;C=Q(F);D=C[0];E=C[1];H.moveTo(D,E);H.click();A('Mouse Clicked At: ('+B(D)+','+B(E)+')')
  File "C:\Program Files (x86)\AMD\Minified.py", line 38, in Q
    def Q(resScreenSize):A=resScreenSize;B=C(A[0],A[1]);D=C(A[2],A[3]);return B,D
  File "C:\Users\Marťas\AppData\Local\Programs\Python\Python310\lib\random.py", line 370, in randint
    return self.randrange(a, b+1)
  File "C:\Users\Marťas\AppData\Local\Programs\Python\Python310\lib\random.py", line 309, in randrange
    raise ValueError("non-integer arg 1 for randrange()")
ValueError: non-integer arg 1 for randrange()

**Comment by InfamyStudio** [comment]
I think I see the issue with the program actually now, possibly the minutes showing up as 0.8333 are trying to be stored in an integer not a float variable and may be causing the crash

**Comment by InfamyStudio** [comment]
pushing a patch now to the github repo for all versions, source, minified, obfuscated - please try the new version V1.3 being pushed now

**Comment by InfamyStudio** [comment]
Version V1.3 is now live - please use the updated version, thank you for reporting this and let me know if this fixes your issue!

**Comment by martas4444** [comment]
I have downloaded new 1.3 version and tried running minified and obfuscated version.
But it keeps failing

Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

== RESTART: C:\Program Files (x86)\AMD\Chipset_Software\AMD helper\Minified.py =
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Using 2560x1440, Changing Randomx and Randomy
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The Default Button Click List Is:
['q', 'w', 'e', 'r', 'a', 's', 'd', 'f']
Would You Like To Add More Keys To The ButtonClickList? Enter (Y) or (N): n
The Button Click List Is: 
['q', 'w', 'e', 'r', 'a', 's', 'd', 'f']
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Usage Just Type an Integer e.g. 30
Please Enter The Shortest Amount of Seconds To Wait Before Input - Recommended (30 seconds): 30
Please Enter The Longest Amount of Seconds To Wait Before Input - Recommended (1200 seconds): 30
This should be not equal to or larger then the lowest amount in range
Please Enter The Shortest Amount of Seconds To Wait Before Input - Recommended (30 seconds): 60
Please Enter The Longest Amount of Seconds To Wait Before Input - Recommended (1200 seconds): 65
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Next Interaction Time: 63 second(s) or 1 minute(s) (Integer Division Not Accurate Minute Representation)!
Traceback (most recent call last):
  File "C:\Users\Marťas\AppData\Local\Programs\Python\Python310\lib\random.py", line 303, in randrange
    istart = _index(start)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\AMD\Chipset_Software\AMD helper\Minified.py", line 60, in <module>
    while F:I(K);R(U);I(K);T(J)
  File "C:\Program Files (x86)\AMD\Chipset_Software\AMD helper\Minified.py", line 39, in R
    def R(retScreenSize):F=retScreenSize;C=Q(F);D=C[0];E=C[1];H.moveTo(D,E);H.click();A('Mouse Clicked At: ('+B(D)+','+B(E)+')')
  File "C:\Program Files (x86)\AMD\Chipset_Software\AMD helper\Minified.py", line 38, in Q
    def Q(resScreenSize):A=resScreenSize;B=C(A[0],A[1]);D=C(A[2],A[3]);return B,D
  File "C:\Users\Marťas\AppData\Local\Programs\Python\Python310\lib\random.py", line 370, in randint
    return self.randrange(a, b+1)
  File "C:\Users\Marťas\AppData\Local\Programs\Python\Python310\lib\random.py", line 309, in randrange
    raise ValueError("non-integer arg 1 for randrange()")
ValueError: non-integer arg 1 for randrange()

**Comment by InfamyStudio** [comment]
I will take a look very soon at this - can you run just Lost Ark Bot non minified, non obfuscated version please.

**Comment by martas4444** [comment]
Sure, result here:

Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

==== RESTART: C:\Program Files (x86)\AMD\Chipset_Software\AMD helper\some.py ===
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Using 2560x1440, Changing Randomx and Randomy
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The Default Button Click List Is:
['q', 'w', 'e', 'r', 'a', 's', 'd', 'f']
Would You Like To Add More Keys To The ButtonClickList? Enter (Y) or (N): n
The Button Click List Is: 
['q', 'w', 'e', 'r', 'a', 's', 'd', 'f']
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Usage Just Type an Integer e.g. 30
Please Enter The Shortest Amount of Seconds To Wait Before Input - Recommended (30 seconds): 30
Please Enter The Longest Amount of Seconds To Wait Before Input - Recommended (1200 seconds): 35
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Next Interaction Time: 33 second(s) or 0 minute(s) (Integer Division Not Accurate Minute Representation)!
Traceback (most recent call last):
  File "C:\Users\Marťas\AppData\Local\Programs\Python\Python310\lib\random.py", line 303, in randrange
    istart = _index(start)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\AMD\Chipset_Software\AMD helper\some.py", line 165, in <module>
    MouseClick(retScreenSize)
  File "C:\Program Files (x86)\AMD\Chipset_Software\AMD helper\some.py", line 102, in MouseClick
    randomlocval = RandomLocationGen(resScreenSize)
  File "C:\Program Files (x86)\AMD\Chipset_Software\AMD helper\some.py", line 97, in RandomLocationGen
    randomy = randint(screenSetup[2],screenSetup[3])
  File "C:\Users\Marťas\AppData\Local\Programs\Python\Python310\lib\random.py", line 370, in randint
    return self.randrange(a, b+1)
  File "C:\Users\Marťas\AppData\Local\Programs\Python\Python310\lib\random.py", line 309, in randrange
    raise ValueError("non-integer arg 1 for randrange()")
ValueError: non-integer arg 1 for randrange()

**Comment by InfamyStudio** [comment]
Fixed now - please try it

**Comment by InfamyStudio** [comment]
one second while I update the minified and obfuscated

**Comment by InfamyStudio** [comment]
Solved now please give it a go!

**Comment by InfamyStudio** [comment]
No do not download version 1.3 - it is not within version 1.3 - download the file directly from the repo.

**Comment by InfamyStudio** [comment]
Let me push a version 1.4

**Comment by InfamyStudio** [comment]
Version 1.4 out download this mate!

**Comment by InfamyStudio** [comment]
Let me know how this goes please!

**Comment by InfamyStudio** [comment]
https://github.com/InfamyStudio/lostArkAntiAFKBot/releases/tag/V1.4

**Comment by martas4444** [comment]
It works! You are the man!
