### ISSUE TITLE
Queue detection 

### ISSUE THREAD

**Issue by Steffen-Bank** [InfamyStudio/lostArkAntiAFKBot#5]
Hello,

I testet the detection with an resolution of 2560x1080 and it doesn't work.
For this resolution I changed the screenshot region to 1028, 435,498,204.
I think launchx for characterlaunch must be 1140 for 2560x1080 resolution. (i didn't test it yet)

I playing in German language. For this language the bot must be looking for 'Warten' and not 'Waiting'.

Can you support multiple languages?

Best regards,
Steffen

**Comment by InfamyStudio** [comment]
Hi Steffen,

Just to confirm them as I do plan to release an update to the Queue Detection system soon. So for the screenshot region is that definitely correct for the 2560x1080 resolution? For the launch button I need the exact location of the centre. Usually the best way to actually make sure the bot clicks it. 

https://pastebin.com/JXSYHQGn

Here is a pastebin to a working screen coordinate python program. You will just need to "run pip install wx" for me. And then you will be able to gather that data and I can push it to release. I have not thought about adding language support but this would be incredibly easy to do as well so I can definitely push support for main region languages of the game. The only issue is py tesseract the system I am using here only detects "English" character set. So anything else may be affected by this. There is  a system called Python OCR which you can specify languages for whatever you are reading from a screen but for myself the project does not have enough attention or need currently for me to implement it. If you feel confident to do that then you can fork the project and I can merge it back into main!

Let me know the exact data results for the window for Queue detection on 2560x1080 and the launch screen cords in the middle of the button.

- InfamyStudio ~ Joe

**Comment by Steffen-Bank** [comment]
Thanks for your reply. I will test tomorrow and send you the coordinates.

**Comment by InfamyStudio** [comment]
Added in further language support for: English
German
Danish
French
Italian
Turkish

When you get me the information on the screen resolutions I will add a new feature passing the Screen Resolution detection function into the Queue Detection system!

**Comment by Steffen-Bank** [comment]
The coordinates are 1180,1014.

**Comment by InfamyStudio** [comment]
Thank you for the information, I will look at releasing an update tomorrow which changes how the screen resolution detection function works, so passing in more data into Queue Detection and Character Launch. I will also check if your resolution is under my "supported" res list. Yeah definitely the ScreenSetup() function should pass this data back through the program as easiest to be calculated and defined at program boot. 

Thank you for your kind words on the program and the Obfuscation and Minified sources run as follows.

Source Code -> https://python-minifier.com/ (Minifies the program) -> https://pyob.oxyry.com/ (Obfuscate the minified source) for best run time speed and security. Minified takes the source from nearly 270 lines to less than 100. Running that through obfuscation does not really add any processing time to the program. I will update here once I have completed the patch and then you can let me know by tests.

**Comment by InfamyStudio** [comment]
V2.5 released! Let me know how it goes.
