### ISSUE TITLE
Add support for 3440 x 1440 resolution

### ISSUE THREAD

**Issue by omares** [InfamyStudio/lostArkAntiAFKBot#7]
Hey, would be lovely if you could add support for the 3440 x 1440 screen resolution.

As documented I used the ScreenCoordinateHelper to grab the x/y coordinates.

Using the tool to measure both the upper left and bottom right point of the box you get the following output:

```
Top-left of bounding box: 1468, 609
Bottom-right of bounding box: 1965, 827
Width, height of bounding box: 497, 218
```

Here are the coordinates you explicitly ask for:

```
Top-left: 1468, 609
Top-middle: 1716, 607
Top-right: 1462, 853
Bottom-left: 1469, 828
Center of box: 1720, 716
```

Cheers

**Comment by InfamyStudio** [comment]
I have tried to add in the queue detection based on these cords, I may re do the way I ask for the cords after I get some feedback from yourself on if the program detects if you are in queue.

**Comment by omares** [comment]
@InfamyStudio Unfortunately, it does not seem to work correctly. At the start, it seems to detect that you are in the queue but after a random period of time, it assumes the queue is done and starts its action albeit queuing is still ongoing.

**Comment by InfamyStudio** [comment]
Is anything blocking the view of the program? As it always needs to be able to read the screen of lost ark. Nothing else can be in the way. In my next update I will change the way I will be asking for cords wants I work out the best way to take and analyse the screen over time. Thinking of changing the program to analyse the whole lost ark program even when minimised.

On 22 Feb 2022, at 16:35, Ota Mares ***@***.***> wrote:

﻿

@InfamyStudio<https://github.com/InfamyStudio> Unfortunately, it does not seem to work correctly. At the start, it seems to detect that you are in the queue but after a random period of time, it assumes the queue is done and starts its action albeit queuing is still ongoing.
