### ISSUE TITLE
Add support for 2560 x 1440 resolution

### ISSUE THREAD

**Issue by pascalbud** [InfamyStudio/lostArkAntiAFKBot#8]
Hello

Thank you for your hard word, could you please add Queue Detection for 2560 x 1440 screen resolution.
```
- Top Left = 1030, 609
- Top Middle = 1278, 609
- Width =  496
- Height = 220
- Centre of the "launch character" box = 1135, 1350
```
ThanksI

**Comment by InfamyStudio** [comment]
Added to next update, please let me know how this works!
