### ISSUE TITLE
Support for 3840x1600 resolution 

### ISSUE THREAD

**Issue by Yarkul7** [InfamyStudio/lostArkAntiAFKBot#9]
To support a screen resolution of 3840x1600 you can use the following settings:

        randomxbot = 590
        randomxtop = 3320
        randomybot = 260
        randomytop = 1350
        launchx = 1760
        launchy = 1500
        scleft = 1642
        sctop = 676
        scwidth = 552
        scheight = 246

**Comment by InfamyStudio** [comment]
Thank you will push this in the next release.
